name: infractl-bind9

services:
  dns-primary:
    image: internetsystemsconsortium/bind9:9.20
    container_name: infractl-dns-primary
    ports:
      - "5301:53/udp"
      - "5301:53/tcp"
    volumes:
      - ./config/primary:/etc/bind:ro
    networks:
      labnet:
        ipv4_address: 172.28.0.10

  dns-secondary:
    image: internetsystemsconsortium/bind9:9.20
    container_name: infractl-dns-secondary
    ports:
      - "5302:53/udp"
      - "5302:53/tcp"
    volumes:
      - ./config/secondary:/etc/bind:ro
      - secondary-cache:/var/cache/bind
    networks:
      labnet:
        ipv4_address: 172.28.0.11

  client:
    image: alpine:3.20
    container_name: infractl-dns-client
    command: sh -c "apk add --no-cache bind-tools iproute2 tcpdump >/dev/null && sleep infinity"
    cap_add:
      - NET_RAW
      - NET_ADMIN
    networks:
      labnet:
        ipv4_address: 172.28.0.20

volumes:
  secondary-cache:

networks:
  labnet:
    ipam:
      config:
        - subnet: 172.28.0.0/24
