include "/etc/bind/tsig.key";

options {
    directory "/var/cache/bind";
    recursion no;
    allow-query { any; };
    listen-on { any; };
    listen-on-v6 { none; };
};

zone "infractl.test" {
    type secondary;
    primaries { 172.28.0.10 key "infractl-xfr"; };
    file "db.infractl.test";
};
