include "/etc/bind/tsig.key";

options {
    directory "/var/cache/bind";
    recursion no;
    allow-query { any; };
    listen-on { any; };
    listen-on-v6 { none; };
};

zone "infractl.test" {
    type primary;
    file "/etc/bind/zones/db.infractl.test";
    allow-transfer { key "infractl-xfr"; };
    notify yes;
};
